[package]
name = "simple-file-cache"
version = "0.2.1"
authors = ["Ivan <ivan.zderadicka@gmail.com>"]
edition = "2018"

[dependencies]
linked-hash-map = "0.5.3"
#filetime = "0.2"
rand = "0.7"
data-encoding = "2.2"
thiserror ="1.0"
log = "0.4"
byteorder = "1.3"

tokio = { version="0.2", optional=true, features=["full"] }


[features]
asynch = ["tokio"]

[dev-dependencies]
env_logger = "0.7"
tempfile ="3.1"


