[package]
name = "websock"
version = "0.2.1"
authors = ["Ivan <ivan.zderadicka@gmail.com>"]
edition = "2018"

[dependencies]

hyper = "0.13"
tokio = {version="0.2", features=["rt-threaded", "macros", "io-util", "fs"]}
futures = "0.3"
log = {version="0.4", features=["max_level_debug"]}
tokio-tungstenite = "0.10"
thiserror = "1.0"
headers = "0.3"

[dev-dependencies]
env_logger = "0.7"